USE BLOODBANKMANAGEMENT;

create table PATIENTS(
PATIENTS_ID int auto_increment,
FIRST_NAME varchar(50),
LAST_NAME varchar(20),
HOSPITAL_NAME varchar(50),
PATIENTS_PHONENUMBER bigint,
PATIENTS_address varchar(200),
BLOODTYPE varchar(20),
primary key (PATIENTS_ID)
);

create table BLOODBANK(
BANK_ID int,
BANK_ADDRESS varchar(200),
BANK_NAME varchar(50),
primary key (BANK_ID)
);

create table RBLOOD_DELIVERY(
PATIENTS_ID int,
BANK_ID int,
FOREIGN KEY (PATIENTS_ID) REFERENCES PATIENTS(PATIENTS_ID),
FOREIGN KEY (BANK_ID) REFERENCES BLOODBANK(BANK_ID)
);
create table DONOR(
GENDER varchar(10),
DONOR_ID int auto_increment,
ADDRESS varchar(200),
DONOR_NAME varchar(50),
BLOODPRESSURE varchar(100),
PHONENUMBER bigint,
DATE_OF_BIRTH varchar(100),
primary key (DONOR_ID)
);

create table BLOOD(
DONOR_ID int,
BLOOD_TYPE varchar(20),
BLOOD_BANK_ID int,
FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID),
FOREIGN KEY (BLOOD_BANK_ID) REFERENCES BLOODBANK(BANK_ID)
);

create table DOCTOR(
DOCTOR_ID int auto_increment,
DOCTOR_NAME varchar(50),
DOCTOR_ADDRESS varchar(200),
primary key (DOCTOR_ID)
);

create table DOCTOR_PHONE(
DOCTOR_ID int,
DOCTOR_PHONENUMBER bigint,
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

create table R_EXAMINES(
DOCTOR_ID int,
DONOR_ID int,
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID)
);