USE BLOODBANKMANAGEMENT;
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'bloodbankmanagement'
AND table_type = 'BASE TABLE';


USE BLOODBANKMANAGEMENT;
SELECT * FROM BLOOD;

USE BLOODBANKMANAGEMENT;
SELECT * FROM BLOODBANK;

USE BLOODBANKMANAGEMENT;
SELECT * FROM DOCTOR;

USE BLOODBANKMANAGEMENT;
SELECT * FROM DOCTOR_PHONE;

USE BLOODBANKMANAGEMENT;
SELECT * FROM DONOR;

USE BLOODBANKMANAGEMENT;
SELECT * FROM PATIENTS;

USE BLOODBANKMANAGEMENT;
SELECT * FROM R_EXAMINES;

USE BLOODBANKMANAGEMENT;
SELECT * FROM RBLOOD_DELIVERY;